### ISSUE TITLE
Where you at?

### ISSUE THREAD

**Issue by dedsecorg** [cnlohr/cnovr#3]
I have been needing an ESPUSB32-driver, you were speaking about making. I hope i did not disturb you in your playground, but was hoping you would take that with a laugh!

Wanna update us? ttps://esp32.com/viewtopic.php?f=13&t=2162&start=10

**Comment by cnlohr** [comment]
It's not gonna happen from me.  Sorry :-/

**Comment by dedsecorg** [comment]
Ahh, okey, then we know atleast. Shit happens! :/
